package com.github.nullptr7

import scala.annotation.*
import scala.quoted.*

/** Field-level metadata */
final case class Min(value: Int) extends StaticAnnotation
final class NonEmpty extends StaticAnnotation

/** Generated by the macro based on the annotations above */
trait Validator[T]:
  def validate(t: T): List[String]

object Validator:
  inline def derived[T]: Validator[T] = ${ ValidatorImpl.derive[T] }

private object ValidatorImpl:
  def derive[T: Type](using quotes: Quotes): Expr[Validator[T]] =
    import quotes.reflect.*

    val tpe: TypeRepr = TypeRepr.of[T]
    val sym: Symbol   = tpe.typeSymbol
    if !sym.isClassDef || !sym.flags.is(Flags.Case) then
      report.errorAndAbort("Validator.derived can only be used for case classes")

    val fields:     List[Symbol] = sym.caseFields
    val ctorParams: List[Symbol] = sym.primaryConstructor.paramSymss.flatten

    // Read annotations from both the accessor and the constructor parameter
    def collectAnnotations(f: Symbol): List[Term] =
      val fromField = f.annotations
      val fromCtor  = ctorParams.find(_.name == f.name).toList.flatMap(_.annotations)
      fromField ++ fromCtor

    // Extract a constant Int argument from an annotation term
    @tailrec
    def constIntArg(t: Term): Option[Int] =
      t match
        case Apply(_, List(Literal(IntConstant(v)))) => Some(v)
        case Inlined(_, _, t1)                       => constIntArg(t1)
        case Typed(t1, _)                            => constIntArg(t1)
        case Block(_, t1)                            => constIntArg(t1)
        case _                                       => None

    def checksExpr(x: Expr[T]): Expr[List[String]] =
      val checks: List[Expr[List[String]]] =
        fields.flatMap { f =>
          val fieldName:          String     = f.name
          val fieldTpe:           TypeRepr   = tpe.memberType(f)
          val fetchedAnnotations: List[Term] = collectAnnotations(f)

          val nonEmptyChecks =
            fetchedAnnotations.collectFirst {
              case ann if ann.tpe =:= TypeRepr.of[NonEmpty] =>
                if !(fieldTpe <:< TypeRepr.of[String]) then
                  report.errorAndAbort(
                    s"@NonEmpty can only be used on String fields, but found $fieldTpe on $fieldName"
                  )
                val fe = Select.unique(x.asTerm, fieldName).asExprOf[String]
                '{
                  if $fe.isEmpty then List(${ Expr(s"$fieldName must be non-empty") })
                  else Nil
                }
            }.toList

          val minChecks =
            fetchedAnnotations.collect {
              case ann if ann.tpe <:< TypeRepr.of[Min] =>
                val n: Int = constIntArg(ann).getOrElse {
                  report.errorAndAbort(s"@Min must have a constant Int value on $fieldName"); 0
                }
                if !(fieldTpe <:< TypeRepr.of[Int]) then
                  report.errorAndAbort(
                    s"@Min can only be used on Int fields, but found $fieldTpe on $fieldName"
                  )
                val fe = Select.unique(x.asTerm, fieldName).asExprOf[Int]
                '{
                  if $fe < ${ Expr(n) } then List(${ Expr(s"$fieldName must be >= $n") })
                  else Nil
                }
            }

          nonEmptyChecks ++ minChecks
        }

      checks match
        case Nil       => '{ Nil: List[String] }
        case h :: tail => tail.foldLeft(h)((acc, e) => '{ $acc ++ $e })

    '{
      new Validator[T]:
        def validate(x: T): List[String] =
          ${ checksExpr('x) }
    }
